import { Injectable } from '@angular/core';

export enum PrioridadeProcesso {
  MAXIMA = 'MÁXIMA',
  ALTA = 'ALTA',
  MEDIA = 'MÉDIA',
  BAIXA = 'BAIXA',
}

export enum NivelSigilo {
  BASICO = 'BÁSICO',
  INTERMEDIARIO = 'INTERMEDIÁRIO',
  TOTAL = 'TOTAL',
}

export interface Processo {
  id: number;
  numero: number;
  numeroFormatado: string;

  niInteressado: string;
  nomeInteressado: string;

  dataProtocolo: Date; // ou Date

  indicadorNotaProcesso: boolean;
  indicadorProvidenciaAberta: boolean;
  indicadorPendenteAssinatura: boolean;
  indicadorPossuiHabilitacaoNivelSigilo: boolean;

  prioridade: PrioridadeProcesso;

  ehResponsavelProcesso: boolean;
  cpfResponsavelAtual: string;

  exibirEmNegrito: boolean;

  dataDistribuicaoUltima: Date; // ou Date

  nivelSigiloInterno: NivelSigilo;
  nivelSigiloExterno: NivelSigilo;

  indicadorNomeNIInteressadoSigiloso: boolean;
}


@Injectable({
  providedIn: 'root'
})
export class DataService {
  public processos: Processo[] = [
    {
        id: 107296,
        numero: 10271000012202564,
        numeroFormatado: "10271.000012/2025-64",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2025-02-26"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2025-02-26"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 100596,
        numero: 10271000014202391,
        numeroFormatado: "10271.000014/2023-91",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2023-01-23"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-01-23"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.INTERMEDIARIO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 91820,
        numero: 13033000001202071,
        numeroFormatado: "13033.000001/2020-71",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2020-07-02"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2020-07-02"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 77337,
        numero: 10040000008031952,
        numeroFormatado: "10040.000008/0319-52",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2019-03-15"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2022-12-28"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 74610,
        numero: 10020000002111861,
        numeroFormatado: "10020.000002/1118-61",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2018-11-22"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2025-07-14"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 66488,
        numero: 10010000002051615,
        numeroFormatado: "10010.000002/0516-15",
        niInteressado: "05037383870",
        nomeInteressado: "YVIZOWL GZWVF ERARYVOOR",
        dataProtocolo: new Date("2016-05-18"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2020-05-20"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.TOTAL,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 63467,
        numero: 10010000010061543,
        numeroFormatado: "10010.000010/0615-43",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2015-06-16"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2016-10-26"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 58417,
        numero: 10010000009041411,
        numeroFormatado: "10010.000009/0414-11",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2014-04-24"),
        indicadorNotaProcesso: true,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2021-04-27"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 58206,
        numero: 10010000002041491,
        numeroFormatado: "10010.000002/0414-91",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2014-04-10"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2020-07-06"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 57380,
        numero: 10010000007011425,
        numeroFormatado: "10010.000007/0114-25",
        niInteressado: "55802141891",
        nomeInteressado: "XOZFWRL UZOOVRILH WRMRA",
        dataProtocolo: new Date("2014-01-23"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2020-03-24"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 57222,
        numero: 10010000041121335,
        numeroFormatado: "10010.000041/1213-35",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2013-12-26"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2020-07-30"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 56913,
        numero: 10020000003121363,
        numeroFormatado: "10020.000003/1213-63",
        niInteressado: "42147496000170",
        nomeInteressado: "MQVIQWDHT U W QMNGUVIQW H KXPHIKQX",
        dataProtocolo: new Date("2013-12-02"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2022-02-03"),
        nivelSigiloInterno: NivelSigilo.TOTAL,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 44209,
        numero: 10010000002051372,
        numeroFormatado: "10010.000002/0513-72",
        niInteressado: "02177963702",
        nomeInteressado: "WLNRMTLH QFHGRML ZOEVH",
        dataProtocolo: new Date("2013-05-03"),
        indicadorNotaProcesso: true,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.MAXIMA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2019-05-31"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 108249,
        numero: 10271000124202515,
        numeroFormatado: "10271.000124/2025-15",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2025-07-11"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2025-07-11"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 106698,
        numero: 10271000230202418,
        numeroFormatado: "10271.000230/2024-18",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2024-11-25"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2024-11-26"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 106551,
        numero: 10271000197202426,
        numeroFormatado: "10271.000197/2024-26",
        niInteressado: "05136946504",
        nomeInteressado: "Florisvaldo",
        dataProtocolo: new Date("2024-10-16"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 106390,
        numero: 10271000187202491,
        numeroFormatado: "10271.000187/2024-91",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2024-10-03"),
        indicadorNotaProcesso: true,
        indicadorProvidenciaAberta: true,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2024-10-03"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 106343,
        numero: 10271000186202446,
        numeroFormatado: "10271.000186/2024-46",
        niInteressado: "05136946504",
        nomeInteressado: "Florisvaldo",
        dataProtocolo: new Date("2024-09-30"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.TOTAL,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: true
    },
    {
        id: 106087,
        numero: 10265000324202476,
        numeroFormatado: "10265.000324/2024-76",
        niInteressado: "76590884000143",
        nomeInteressado: "GMQPHN NX HUVWNX NH UWMVW KWVWIQMW WHNHIWKWX HUVWNGWD NWU KXXFHIWVQEWU PHNQKWU",
        dataProtocolo: new Date("2024-08-21"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2025-09-30"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 101938,
        numero: 10518720053202379,
        numeroFormatado: "10518.720053/2023-79",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2023-07-11"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-07-11"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 101256,
        numero: 10271000037202304,
        numeroFormatado: "10271.000037/2023-04",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2023-03-22"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: false,
        cpfResponsavelAtual: "39148920720",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 101056,
        numero: 10271000029202350,
        numeroFormatado: "10271.000029/2023-50",
        niInteressado: "null",
        nomeInteressado: "Teste CIENCIA",
        dataProtocolo: new Date("2023-02-19"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-03-09"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 100778,
        numero: 10518720013202327,
        numeroFormatado: "10518.720013/2023-27",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2023-02-08"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-02-08"),
        nivelSigiloInterno: NivelSigilo.TOTAL,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 100759,
        numero: 10518720008202314,
        numeroFormatado: "10518.720008/2023-14",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2023-02-07"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: true,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2023-02-07"),
        nivelSigiloInterno: NivelSigilo.INTERMEDIARIO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 100556,
        numero: 10271000012202301,
        numeroFormatado: "10271.000012/2023-01",
        niInteressado: "59311207853",
        nomeInteressado: "QLHV VWTZI ZOEVH KRMSVRIL",
        dataProtocolo: new Date("2023-01-13"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: false,
        cpfResponsavelAtual: "39148920720",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 100536,
        numero: 10271000011202358,
        numeroFormatado: "10271.000011/2023-58",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2023-01-13"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: false,
        cpfResponsavelAtual: "39148920720",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 100476,
        numero: 10271000010202311,
        numeroFormatado: "10271.000010/2023-11",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2023-01-09"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2024-08-05"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97715,
        numero: 10271000039202212,
        numeroFormatado: "10271.000039/2022-12",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2022-07-05"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: false,
        cpfResponsavelAtual: "39148920720",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97515,
        numero: 10271000038202260,
        numeroFormatado: "10271.000038/2022-60",
        niInteressado: "05037383870",
        nomeInteressado: "YVIZOWL GZWVF ERARYVOOR",
        dataProtocolo: new Date("2022-06-01"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: false,
        cpfResponsavelAtual: "39148920720",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97415,
        numero: 10271000036202271,
        numeroFormatado: "10271.000036/2022-71",
        niInteressado: "05037383870",
        nomeInteressado: "YVIZOWL GZWVF ERARYVOOR",
        dataProtocolo: new Date("2022-05-12"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-05-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97375,
        numero: 10271000031202248,
        numeroFormatado: "10271.000031/2022-48",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2022-04-07"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: false,
        cpfResponsavelAtual: "39148920720",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2025-05-15"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97355,
        numero: 10271000030202201,
        numeroFormatado: "10271.000030/2022-01",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2022-04-07"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: true,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2022-10-17"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97296,
        numero: 10271000028202224,
        numeroFormatado: "10271.000028/2022-24",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2022-04-04"),
        indicadorNotaProcesso: true,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2022-04-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97082,
        numero: 11020720025202225,
        numeroFormatado: "11020.720025/2022-25",
        niInteressado: "07498804000101",
        nomeInteressado: "WGMNQWWI PHVWDGIBQW DVNW - HP IHKGFHIWKWX RGNQKQWD",
        dataProtocolo: new Date("2022-03-22"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2022-03-28"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 97083,
        numero: 10880720075202210,
        numeroFormatado: "10880.720075/2022-10",
        niInteressado: "38344633885",
        nomeInteressado: "XRWROZRMV WZ HROEZ",
        dataProtocolo: new Date("2022-03-22"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2022-03-28"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 93975,
        numero: 10271000057202024,
        numeroFormatado: "10271.000057/2020-24",
        niInteressado: "05136946504",
        nomeInteressado: "FLORISVALDO FELICIO DE CARVALHO",
        dataProtocolo: new Date("2020-11-20"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2021-02-03"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 92568,
        numero: 10168100052202088,
        numeroFormatado: "10168.100052/2020-88",
        niInteressado: "00000000000000",
        nomeInteressado: "null",
        dataProtocolo: new Date("2020-08-18"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-03-09"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 82253,
        numero: 10265006406202009,
        numeroFormatado: "10265.006406/2020-09",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2020-03-16"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-03-13"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 78072,
        numero: 10020000003041921,
        numeroFormatado: "10020.000003/0419-21",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2019-04-02"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2023-05-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 77903,
        numero: 10040000575031917,
        numeroFormatado: "10040.000575/0319-17",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2019-03-15"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2023-05-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 73655,
        numero: 10580720015201803,
        numeroFormatado: "10580.720015/2018-03",
        niInteressado: "07453611000134",
        nomeInteressado: "KXPHIKQWD BIWMNH GMQWX HQIHDQ",
        dataProtocolo: new Date("2018-09-12"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2018-09-26"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 72750,
        numero: 10020000021041821,
        numeroFormatado: "10020.000021/0418-21",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2018-04-20"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-05-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 72756,
        numero: 10020000027041807,
        numeroFormatado: "10020.000027/0418-07",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2018-04-20"),
        indicadorNotaProcesso: true,
        indicadorProvidenciaAberta: true,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-05-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 72755,
        numero: 10020000026041854,
        numeroFormatado: "10020.000026/0418-54",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2018-04-20"),
        indicadorNotaProcesso: true,
        indicadorProvidenciaAberta: true,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: true,
        dataDistribuicaoUltima: new Date("2023-05-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 72766,
        numero: 10020000037041834,
        numeroFormatado: "10020.000037/0418-34",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2018-04-20"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2023-05-04"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 72708,
        numero: 17787720450201771,
        numeroFormatado: "17787.720450/2017-71",
        niInteressado: "01655459000196",
        nomeInteressado: "UHIEH-IQX UHIEQKXU HUFHKQWDQSWNXU DVNW - HFF",
        dataProtocolo: new Date("2017-12-27"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2018-04-05"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 71949,
        numero: 10010000052091734,
        numeroFormatado: "10010.000052/0917-34",
        niInteressado: "00000004006",
        nomeInteressado: "EZTMVI ZOVCZMWIV IRTL",
        dataProtocolo: new Date("2017-09-28"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2022-05-19"),
        nivelSigiloInterno: NivelSigilo.INTERMEDIARIO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 71917,
        numero: 10880729087201742,
        numeroFormatado: "10880.729087/2017-42",
        niInteressado: "02558157000162",
        nomeInteressado: "VHDHWXMQKW OIWUQD U.W.",
        dataProtocolo: new Date("2017-09-26"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2018-06-21"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 68448,
        numero: 10010000001011709,
        numeroFormatado: "10010.000001/0117-09",
        niInteressado: "05136946504",
        nomeInteressado: "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
        dataProtocolo: new Date("2017-01-05"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2017-01-25"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    },
    {
        id: 64973,
        numero: 10510000048201514,
        numeroFormatado: "10510.000048/2015-14",
        niInteressado: "00012008877",
        nomeInteressado: "NZIXRZ NZIGRMH TLMXZOEVH",
        dataProtocolo: new Date("2015-11-03"),
        indicadorNotaProcesso: false,
        indicadorProvidenciaAberta: false,
        indicadorPendenteAssinatura: false,
        indicadorPossuiHabilitacaoNivelSigilo: false,
        prioridade: PrioridadeProcesso.ALTA,
        ehResponsavelProcesso: true,
        cpfResponsavelAtual: "05136946504",
        exibirEmNegrito: false,
        dataDistribuicaoUltima: new Date("2016-01-29"),
        nivelSigiloInterno: NivelSigilo.BASICO,
        nivelSigiloExterno: NivelSigilo.BASICO,
        indicadorNomeNIInteressadoSigiloso: false
    }
]

  constructor() { }

  mapProcesso(raw: any): Processo {
    return {
      ...raw,
      dataProtocolo: new Date(raw.dataProtocolo),
      dataDistribuicaoUltima: new Date(raw.dataDistribuicaoUltima),
    };
  }

  public getProcessos(): Processo[] {
    return this.processos.map(p => this.mapProcesso(p));
  }

  public getProcessoById(id: number): Processo {
    return this.processos[id];
  }
}


