import { Injectable } from '@angular/core';
import {
  Processo,
  ProcessoRaw,
  PrioridadeProcesso,
  NivelSigilo
} from './models/processo.model';
import { ApiResponse } from './models/api-response.model';

@Injectable({
  providedIn: 'root',
})
export class DataService {

  /* =========================
   * ESTADO INTERNO
   * ========================= */

  private response: ApiResponse = {
    "quantidadeProcessos": 7941,
    "processos": [
        {
            "id": 107296,
            "numero": "10271000012202564",
            "numeroFormatado": "10271.000012/2025-64",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "26/02/2025",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "26/02/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 100596,
            "numero": "10271000014202391",
            "numeroFormatado": "10271.000014/2023-91",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "23/01/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "23/01/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "INTERMEDIÁRIO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 91820,
            "numero": "13033000001202071",
            "numeroFormatado": "13033.000001/2020-71",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "02/07/2020",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "02/07/2020",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 77337,
            "numero": "10040000008031952",
            "numeroFormatado": "10040.000008/0319-52",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "15/03/2019",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "28/12/2022",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 74610,
            "numero": "10020000002111861",
            "numeroFormatado": "10020.000002/1118-61",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "22/11/2018",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "14/07/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 66488,
            "numero": "10010000002051615",
            "numeroFormatado": "10010.000002/0516-15",
            "niInteressado": "05037383870",
            "nomeInteressado": "YVIZOWL GZWVF ERARYVOOR",
            "dataProtocolo": "18/05/2016",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "20/05/2020",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "TOTAL",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 63467,
            "numero": "10010000010061543",
            "numeroFormatado": "10010.000010/0615-43",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "16/06/2015",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "26/10/2016",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 58417,
            "numero": "10010000009041411",
            "numeroFormatado": "10010.000009/0414-11",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "24/04/2014",
            "indicadorNotaProcesso": true,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "27/04/2021",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 58206,
            "numero": "10010000002041491",
            "numeroFormatado": "10010.000002/0414-91",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "10/04/2014",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "06/07/2020",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 57380,
            "numero": "10010000007011425",
            "numeroFormatado": "10010.000007/0114-25",
            "niInteressado": "55802141891",
            "nomeInteressado": "XOZFWRL UZOOVRILH WRMRA",
            "dataProtocolo": "23/01/2014",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "24/03/2020",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 57222,
            "numero": "10010000041121335",
            "numeroFormatado": "10010.000041/1213-35",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "26/12/2013",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "30/07/2020",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 56913,
            "numero": "10020000003121363",
            "numeroFormatado": "10020.000003/1213-63",
            "niInteressado": "42147496000170",
            "nomeInteressado": "MQVIQWDHT U W QMNGUVIQW H KXPHIKQX",
            "dataProtocolo": "02/12/2013",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "03/02/2022",
            "nivelSigiloInterno": "TOTAL",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 44209,
            "numero": "10010000002051372",
            "numeroFormatado": "10010.000002/0513-72",
            "niInteressado": "02177963702",
            "nomeInteressado": "WLNRMTLH QFHGRML ZOEVH",
            "dataProtocolo": "03/05/2013",
            "indicadorNotaProcesso": true,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "MAXIMA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "31/05/2019",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 108249,
            "numero": "10271000124202515",
            "numeroFormatado": "10271.000124/2025-15",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "11/07/2025",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "11/07/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 106698,
            "numero": "10271000230202418",
            "numeroFormatado": "10271.000230/2024-18",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "25/11/2024",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "26/11/2024",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 106551,
            "numero": "10271000197202426",
            "numeroFormatado": "10271.000197/2024-26",
            "niInteressado": "05136946504",
            "nomeInteressado": "Florisvaldo",
            "dataProtocolo": "16/10/2024",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 106390,
            "numero": "10271000187202491",
            "numeroFormatado": "10271.000187/2024-91",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "03/10/2024",
            "indicadorNotaProcesso": true,
            "indicadorProvidenciaAberta": true,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "03/10/2024",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 106343,
            "numero": "10271000186202446",
            "numeroFormatado": "10271.000186/2024-46",
            "niInteressado": "05136946504",
            "nomeInteressado": "Florisvaldo",
            "dataProtocolo": "30/09/2024",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "TOTAL",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": true
        },
        {
            "id": 106087,
            "numero": "10265000324202476",
            "numeroFormatado": "10265.000324/2024-76",
            "niInteressado": "76590884000143",
            "nomeInteressado": "GMQPHN NX HUVWNX NH UWMVW KWVWIQMW WHNHIWKWX HUVWNGWD NWU KXXFHIWVQEWU PHNQKWU",
            "dataProtocolo": "21/08/2024",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "30/09/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 101938,
            "numero": "10518720053202379",
            "numeroFormatado": "10518.720053/2023-79",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "11/07/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "11/07/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 101256,
            "numero": "10271000037202304",
            "numeroFormatado": "10271.000037/2023-04",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "22/03/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": false,
            "cpfResponsavelAtual": "39148920720",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 101056,
            "numero": "10271000029202350",
            "numeroFormatado": "10271.000029/2023-50",
            "niInteressado": "05136946504",
            "nomeInteressado": "Teste CIENCIA",
            "dataProtocolo": "19/02/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "09/03/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 100778,
            "numero": "10518720013202327",
            "numeroFormatado": "10518.720013/2023-27",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "08/02/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "08/02/2023",
            "nivelSigiloInterno": "TOTAL",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 100759,
            "numero": "10518720008202314",
            "numeroFormatado": "10518.720008/2023-14",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "07/02/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": true,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "07/02/2023",
            "nivelSigiloInterno": "INTERMEDIÁRIO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 100556,
            "numero": "10271000012202301",
            "numeroFormatado": "10271.000012/2023-01",
            "niInteressado": "59311207853",
            "nomeInteressado": "QLHV VWTZI ZOEVH KRMSVRIL",
            "dataProtocolo": "13/01/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": false,
            "cpfResponsavelAtual": "39148920720",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 100536,
            "numero": "10271000011202358",
            "numeroFormatado": "10271.000011/2023-58",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "13/01/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": false,
            "cpfResponsavelAtual": "39148920720",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 100476,
            "numero": "10271000010202311",
            "numeroFormatado": "10271.000010/2023-11",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "09/01/2023",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "05/08/2024",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97715,
            "numero": "10271000039202212",
            "numeroFormatado": "10271.000039/2022-12",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "05/07/2022",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": false,
            "cpfResponsavelAtual": "39148920720",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97515,
            "numero": "10271000038202260",
            "numeroFormatado": "10271.000038/2022-60",
            "niInteressado": "05037383870",
            "nomeInteressado": "YVIZOWL GZWVF ERARYVOOR",
            "dataProtocolo": "01/06/2022",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": false,
            "cpfResponsavelAtual": "39148920720",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97415,
            "numero": "10271000036202271",
            "numeroFormatado": "10271.000036/2022-71",
            "niInteressado": "05037383870",
            "nomeInteressado": "YVIZOWL GZWVF ERARYVOOR",
            "dataProtocolo": "12/05/2022",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "04/05/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97375,
            "numero": "10271000031202248",
            "numeroFormatado": "10271.000031/2022-48",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "07/04/2022",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": false,
            "cpfResponsavelAtual": "39148920720",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "15/05/2025",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97355,
            "numero": "10271000030202201",
            "numeroFormatado": "10271.000030/2022-01",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "07/04/2022",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": true,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "17/10/2022",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97296,
            "numero": "10271000028202224",
            "numeroFormatado": "10271.000028/2022-24",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "04/04/2022",
            "indicadorNotaProcesso": true,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "04/04/2022",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97082,
            "numero": "11020720025202225",
            "numeroFormatado": "11020.720025/2022-25",
            "niInteressado": "07498804000101",
            "nomeInteressado": "WGMNQWWI PHVWDGIBQW DVNW - HP IHKGFHIWKWX RGNQKQWD",
            "dataProtocolo": "22/03/2022",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "28/03/2022",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 97083,
            "numero": "10880720075202210",
            "numeroFormatado": "10880.720075/2022-10",
            "niInteressado": "38344633885",
            "nomeInteressado": "XRWROZRMV WZ HROEZ",
            "dataProtocolo": "22/03/2022",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "28/03/2022",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 93975,
            "numero": "10271000057202024",
            "numeroFormatado": "10271.000057/2020-24",
            "niInteressado": "05136946504",
            "nomeInteressado": "FLORISVALDO FELICIO DE CARVALHO",
            "dataProtocolo": "20/11/2020",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "03/02/2021",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 92568,
            "numero": "10168100052202088",
            "numeroFormatado": "10168.100052/2020-88",
            "niInteressado": "00000000000000",
            "nomeInteressado": "05136946504",
            "dataProtocolo": "18/08/2020",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "09/03/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 82253,
            "numero": "10265006406202009",
            "numeroFormatado": "10265.006406/2020-09",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "16/03/2020",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "13/03/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 78072,
            "numero": "10020000003041921",
            "numeroFormatado": "10020.000003/0419-21",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "02/04/2019",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "04/05/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 77903,
            "numero": "10040000575031917",
            "numeroFormatado": "10040.000575/0319-17",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "15/03/2019",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "04/05/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 73655,
            "numero": "10580720015201803",
            "numeroFormatado": "10580.720015/2018-03",
            "niInteressado": "07453611000134",
            "nomeInteressado": "KXPHIKQWD BIWMNH GMQWX HQIHDQ",
            "dataProtocolo": "12/09/2018",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "26/09/2018",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 72750,
            "numero": "10020000021041821",
            "numeroFormatado": "10020.000021/0418-21",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "20/04/2018",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "04/05/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 72756,
            "numero": "10020000027041807",
            "numeroFormatado": "10020.000027/0418-07",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "20/04/2018",
            "indicadorNotaProcesso": true,
            "indicadorProvidenciaAberta": true,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "04/05/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 72755,
            "numero": "10020000026041854",
            "numeroFormatado": "10020.000026/0418-54",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "20/04/2018",
            "indicadorNotaProcesso": true,
            "indicadorProvidenciaAberta": true,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": true,
            "dataDistribuicaoUltima": "04/05/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 72766,
            "numero": "10020000037041834",
            "numeroFormatado": "10020.000037/0418-34",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "20/04/2018",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "04/05/2023",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 72708,
            "numero": "17787720450201771",
            "numeroFormatado": "17787.720450/2017-71",
            "niInteressado": "01655459000196",
            "nomeInteressado": "UHIEH-IQX UHIEQKXU HUFHKQWDQSWNXU DVNW - HFF",
            "dataProtocolo": "27/12/2017",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "05/04/2018",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 71949,
            "numero": "10010000052091734",
            "numeroFormatado": "10010.000052/0917-34",
            "niInteressado": "00000004006",
            "nomeInteressado": "EZTMVI ZOVCZMWIV IRTL",
            "dataProtocolo": "28/09/2017",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "19/05/2022",
            "nivelSigiloInterno": "INTERMEDIÁRIO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 71917,
            "numero": "10880729087201742",
            "numeroFormatado": "10880.729087/2017-42",
            "niInteressado": "02558157000162",
            "nomeInteressado": "VHDHWXMQKW OIWUQD U.W.",
            "dataProtocolo": "26/09/2017",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "21/06/2018",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 68448,
            "numero": "10010000001011709",
            "numeroFormatado": "10010.000001/0117-09",
            "niInteressado": "05136946504",
            "nomeInteressado": "UOLIRHEZOWL UVORXRL WV XZIEZOSL",
            "dataProtocolo": "05/01/2017",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "25/01/2017",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        },
        {
            "id": 64973,
            "numero": "10510000048201514",
            "numeroFormatado": "10510.000048/2015-14",
            "niInteressado": "00012008877",
            "nomeInteressado": "NZIXRZ NZIGRMH TLMXZOEVH",
            "dataProtocolo": "03/11/2015",
            "indicadorNotaProcesso": false,
            "indicadorProvidenciaAberta": false,
            "indicadorPendenteAssinatura": false,
            "indicadorPossuiHabilitacaoNivelSigilo": false,
            "prioridade": "ALTA",
            "ehResponsavelProcesso": true,
            "cpfResponsavelAtual": "05136946504",
            "exibirEmNegrito": false,
            "dataDistribuicaoUltima": "29/01/2016",
            "nivelSigiloInterno": "BÁSICO",
            "nivelSigiloExterno": "BÁSICO",
            "indicadorNomeNIInteressadoSigiloso": false
        }
    ]
};
  private processosRaw: ProcessoRaw[] = [];
  private processos: Processo[] = [];

  constructor() {}

  /* =========================
   * LOAD (API → DOMÍNIO)
   * ========================= */

  load(response: ApiResponse): void {
    this.processosRaw = response.processos;
    this.processos = response.processos.map(p => this.mapProcesso(p));
  }

  /* =========================
   * GETTERS
   * ========================= */

  getProcessos(): Processo[] {
    return this.response.processos.map(p => this.mapProcesso(p));
    }

    getQuantidadeProcessos(): number {
    return this.response.quantidadeProcessos;
    }

    getProcessoById(id: number): Processo | undefined {
  return this.processos.find(p => p.id === id);
}

  /* =========================
   * PARSERS
   * ========================= */

  private parseDate(date: string): Date {
    if (!date) return null as any;

    const [day, month, year] = date.split('/');
    return new Date(Number(year), Number(month) - 1, Number(day));
  }

  private parsePrioridade(value: string): PrioridadeProcesso {
    switch (value) {
      case 'MAXIMA':
        return PrioridadeProcesso.MAXIMA;
      case 'ALTA':
        return PrioridadeProcesso.ALTA;
      case 'MEDIA':
        return PrioridadeProcesso.MEDIA;
      case 'BAIXA':
        return PrioridadeProcesso.BAIXA;
      default:
        throw new Error(`Prioridade desconhecida: ${value}`);
    }
  }

  private parseNivelSigilo(value: string): NivelSigilo {
    return value as NivelSigilo;
  }

  /* =========================
   * MAPPER
   * ========================= */

  private mapProcesso(raw: ProcessoRaw): Processo {
    return {
      id: raw.id,
      numero: Number(raw.numero),
      numeroFormatado: raw.numeroFormatado,

      niInteressado: raw.niInteressado,
      nomeInteressado: raw.nomeInteressado,

      dataProtocolo: this.parseDate(raw.dataProtocolo),
      dataDistribuicaoUltima: this.parseDate(raw.dataDistribuicaoUltima),

      indicadorNotaProcesso: raw.indicadorNotaProcesso,
      indicadorProvidenciaAberta: raw.indicadorProvidenciaAberta,
      indicadorPendenteAssinatura: raw.indicadorPendenteAssinatura,
      indicadorPossuiHabilitacaoNivelSigilo: raw.indicadorPossuiHabilitacaoNivelSigilo,

      prioridade: this.parsePrioridade(raw.prioridade),

      ehResponsavelProcesso: raw.ehResponsavelProcesso,
      cpfResponsavelAtual: raw.cpfResponsavelAtual,
      exibirEmNegrito: raw.exibirEmNegrito,

      nivelSigiloInterno: this.parseNivelSigilo(raw.nivelSigiloInterno),
      nivelSigiloExterno: this.parseNivelSigilo(raw.nivelSigiloExterno),

      indicadorNomeNIInteressadoSigiloso: raw.indicadorNomeNIInteressadoSigiloso,
    };
  }
}
